import React, { useState, useEffect } from 'react';
import { Calendar, Search, Plus, X, ChevronDown, ChevronRight, Edit2, Trash2, Check, Clock, Plane, Users, FileText, ListTodo, Mic, Send, Bot, Upload, Download, Eye, MessageSquare } from 'lucide-react';

// Color palette from uploaded image
const colors = {
  primary: '#1A2B45',      // Deep Midnight Blue
  secondary: '#D4AF37',    // Champagne Gold
  tertiary: '#8E8D8A',     // Warm Grey
  dark: '#2F02F',          // Charcoal Black
  silver: '#C01620',       // Subtle Silver
  accent: '#1400F'         // Sihler
};

const JetCRM = () => {
  // State Management
  const [activeTab, setActiveTab] = useState('dashboard');
  const [leads, setLeads] = useState([
    { 
      id: 1, 
      name: 'John Smith', 
      company: 'Tech Corp', 
      aircraftType: 'Midsize Jet',
      budget: 8000000,
      budgetKnown: true,
      yearPreference: { oldest: 2015, newest: 2023 },
      status: 'Hot',
      presentations: [],
      createdAt: '2025-01-15',
      notes: 'Looking for immediate purchase'
    },
    { 
      id: 2, 
      name: 'Sarah Johnson', 
      company: 'Global Ventures', 
      aircraftType: 'Heavy Jet',
      budget: null,
      budgetKnown: false,
      yearPreference: { oldest: 2018, newest: 2025 },
      status: 'Warm',
      presentations: [],
      createdAt: '2025-02-10',
      notes: 'Flexible on specifications'
    }
  ]);

  const [aircraft, setAircraft] = useState([
    {
      id: 1,
      manufacturer: 'Gulfstream',
      model: 'G650ER',
      yom: 2020,
      serialNumber: 'SN-6350',
      registration: 'N650GS',
      category: 'Heavy Jet',
      location: 'Van Nuys, CA',
      price: 65000000,
      specSheet: null,
      presentations: [],
      accessType: 'Direct',
      createdAt: '2025-01-20'
    },
    {
      id: 2,
      manufacturer: 'Bombardier',
      model: 'Global 7500',
      yom: 2022,
      serialNumber: 'SN-75100',
      registration: 'N7500BD',
      category: 'Heavy Jet',
      location: 'Teterboro, NJ',
      price: 73000000,
      specSheet: null,
      presentations: [],
      accessType: 'Broker',
      createdAt: '2025-01-25'
    }
  ]);

  const [deals, setDeals] = useState([
    {
      id: 1,
      dealName: 'Smith G650ER Acquisition',
      clientName: 'John Smith',
      relatedLead: 1,
      relatedAircraft: 1,
      dealValue: 65000000,
      estimatedClosing: '2025-04-15',
      status: 'Negotiation',
      nextStep: 'Schedule pre-purchase inspection',
      followUpDate: '2025-03-20',
      createdAt: '2025-03-01',
      history: []
    }
  ]);

  const [tasks, setTasks] = useState([
    {
      id: 1,
      title: 'Schedule pre-purchase inspection',
      description: 'Coordinate with maintenance facility for G650ER inspection',
      dueDate: '2025-03-20',
      relatedTo: { type: 'deal', id: 1 },
      status: 'pending',
      priority: 'high',
      createdAt: '2025-03-01',
      autoGenerated: true
    },
    {
      id: 2,
      title: 'Follow up with Sarah Johnson',
      description: 'Discuss Global 7500 presentation feedback',
      dueDate: '2025-03-15',
      relatedTo: { type: 'lead', id: 2 },
      status: 'pending',
      priority: 'medium',
      createdAt: '2025-03-10',
      autoGenerated: false
    }
  ]);

  const [showModal, setShowModal] = useState(false);
  const [modalType, setModalType] = useState('');
  const [editingItem, setEditingItem] = useState(null);
  const [aiInput, setAiInput] = useState('');
  const [aiMessages, setAiMessages] = useState([]);
  const [isAiThinking, setIsAiThinking] = useState(false);
  const [filterStatus, setFilterStatus] = useState('all');
  const [searchTerm, setSearchTerm] = useState('');
  const [calendarView, setCalendarView] = useState(false);

  // Modal handlers
  const openModal = (type, item = null) => {
    setModalType(type);
    setEditingItem(item);
    setShowModal(true);
  };

  const closeModal = () => {
    setShowModal(false);
    setModalType('');
    setEditingItem(null);
  };

  // CRUD Operations
  const addLead = (leadData) => {
    const newLead = {
      id: leads.length + 1,
      ...leadData,
      presentations: [],
      createdAt: new Date().toISOString().split('T')[0]
    };
    setLeads([...leads, newLead]);
    createAutoTask('lead', newLead.id, `Follow up with ${leadData.name}`);
  };

  const updateLead = (id, updatedData) => {
    setLeads(leads.map(lead => lead.id === id ? { ...lead, ...updatedData } : lead));
  };

  const deleteLead = (id) => {
    setLeads(leads.filter(lead => lead.id !== id));
  };

  const addAircraft = (aircraftData) => {
    const newAircraft = {
      id: aircraft.length + 1,
      ...aircraftData,
      presentations: [],
      createdAt: new Date().toISOString().split('T')[0]
    };
    setAircraft([...aircraft, newAircraft]);
  };

  const updateAircraft = (id, updatedData) => {
    setAircraft(aircraft.map(ac => ac.id === id ? { ...ac, ...updatedData } : ac));
  };

  const deleteAircraft = (id) => {
    setAircraft(aircraft.filter(ac => ac.id !== id));
  };

  const addDeal = (dealData) => {
    const newDeal = {
      id: deals.length + 1,
      ...dealData,
      createdAt: new Date().toISOString().split('T')[0],
      history: [{ date: new Date().toISOString(), action: 'Deal created', status: dealData.status }]
    };
    setDeals([...deals, newDeal]);
    createAutoTask('deal', newDeal.id, newDeal.nextStep, newDeal.followUpDate);
  };

  const updateDealStatus = (id, newStatus) => {
    const deal = deals.find(d => d.id === id);
    const nextSteps = {
      'Lead': { step: 'Initial contact and qualification', days: 3 },
      'Qualification': { step: 'Present aircraft options', days: 5 },
      'Presentation': { step: 'Schedule viewing/demo flight', days: 7 },
      'Negotiation': { step: 'Finalize terms and conditions', days: 10 },
      'Pre-Purchase': { step: 'Complete pre-purchase inspection', days: 14 },
      'Closing': { step: 'Finalize paperwork and payment', days: 7 },
      'Closed Won': { step: 'Post-sale follow-up', days: 30 },
      'Closed Lost': { step: 'Archive and analyze', days: 1 }
    };

    const nextStep = nextSteps[newStatus];
    const followUpDate = new Date();
    followUpDate.setDate(followUpDate.getDate() + nextStep.days);

    const updatedDeal = {
      ...deal,
      status: newStatus,
      nextStep: nextStep.step,
      followUpDate: followUpDate.toISOString().split('T')[0],
      history: [...deal.history, { 
        date: new Date().toISOString(), 
        action: `Status changed to ${newStatus}`, 
        status: newStatus 
      }]
    };

    setDeals(deals.map(d => d.id === id ? updatedDeal : d));
    createAutoTask('deal', id, nextStep.step, followUpDate.toISOString().split('T')[0]);
  };

  const deleteDeal = (id) => {
    setDeals(deals.filter(deal => deal.id !== id));
  };

  const presentAircraftToLead = (leadId, aircraftId, notes, price) => {
    const presentation = {
      aircraftId,
      date: new Date().toISOString(),
      notes,
      priceGiven: price
    };

    setLeads(leads.map(lead => 
      lead.id === leadId 
        ? { ...lead, presentations: [...lead.presentations, presentation] }
        : lead
    ));

    setAircraft(aircraft.map(ac =>
      ac.id === aircraftId
        ? { ...ac, presentations: [...ac.presentations, { leadId, date: presentation.date, notes }] }
        : ac
    ));

    createAutoTask('presentation', leadId, `Follow up on aircraft presentation to ${leads.find(l => l.id === leadId)?.name}`);
  };

  const createAutoTask = (type, relatedId, title, dueDate = null) => {
    const taskDueDate = dueDate || new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString().split('T')[0];
    const newTask = {
      id: tasks.length + 1,
      title,
      description: `Auto-generated task for ${type}`,
      dueDate: taskDueDate,
      relatedTo: { type, id: relatedId },
      status: 'pending',
      priority: 'medium',
      createdAt: new Date().toISOString().split('T')[0],
      autoGenerated: true
    };
    setTasks([...tasks, newTask]);
  };

  const addTask = (taskData) => {
    const newTask = {
      id: tasks.length + 1,
      ...taskData,
      createdAt: new Date().toISOString().split('T')[0],
      autoGenerated: false
    };
    setTasks([...tasks, newTask]);
  };

  const updateTask = (id, updatedData) => {
    setTasks(tasks.map(task => task.id === id ? { ...task, ...updatedData } : task));
  };

  const deleteTask = (id) => {
    setTasks(tasks.filter(task => task.id !== id));
  };

  // AI Assistant
  const handleAiMessage = async () => {
    if (!aiInput.trim()) return;

    const userMessage = { role: 'user', content: aiInput };
    setAiMessages([...aiMessages, userMessage]);
    setIsAiThinking(true);
    setAiInput('');

    // Simulate AI processing and action
    setTimeout(() => {
      let response = { role: 'assistant', content: '', action: null };

      const input = aiInput.toLowerCase();

      if (input.includes('create') && input.includes('lead')) {
        response.content = "I'll help you create a new lead. Opening the lead creation form...";
        response.action = () => openModal('lead');
      } else if (input.includes('show') && input.includes('task')) {
        response.content = "Switching to tasks view to show all your pending tasks.";
        response.action = () => setActiveTab('tasks');
      } else if (input.includes('aircraft') && input.includes('available')) {
        response.content = `You currently have ${aircraft.length} aircraft in your inventory. ${aircraft.filter(ac => ac.presentations.length === 0).length} have not been presented yet.`;
      } else if (input.includes('deal') && (input.includes('status') || input.includes('update'))) {
        response.content = `You have ${deals.length} active deals. ${deals.filter(d => d.status === 'Negotiation').length} are in negotiation phase.`;
        response.action = () => setActiveTab('deals');
      } else if (input.includes('present') && input.includes('aircraft')) {
        response.content = "To present an aircraft to a lead, go to the Aircraft section and click the 'Present to Lead' button on the aircraft card.";
        response.action = () => setActiveTab('aircraft');
      } else if (input.includes('report') || input.includes('summary')) {
        response.content = `Here's a quick summary:\n• Leads: ${leads.length} (${leads.filter(l => l.status === 'Hot').length} hot)\n• Aircraft: ${aircraft.length}\n• Active Deals: ${deals.length}\n• Pending Tasks: ${tasks.filter(t => t.status === 'pending').length}`;
      } else {
        response.content = "I can help you with:\n• Creating leads, aircraft, deals, or tasks\n• Presenting aircraft to leads\n• Updating deal statuses\n• Viewing summaries and reports\n\nWhat would you like to do?";
      }

      setAiMessages(prev => [...prev, response]);
      setIsAiThinking(false);

      if (response.action) {
        setTimeout(response.action, 500);
      }
    }, 1500);
  };

  // Dashboard Component
  const Dashboard = () => {
    const hotLeads = leads.filter(l => l.status === 'Hot').length;
    const activeDeals = deals.filter(d => !['Closed Won', 'Closed Lost'].includes(d.status)).length;
    const pendingTasks = tasks.filter(t => t.status === 'pending').length;
    const totalInventory = aircraft.length;

    return (
      <div className="space-y-6">
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
          <StatCard 
            icon={<Users size={32} />} 
            title="Hot Leads" 
            value={hotLeads} 
            total={leads.length}
            color={colors.secondary}
          />
          <StatCard 
            icon={<FileText size={32} />} 
            title="Active Deals" 
            value={activeDeals} 
            total={deals.length}
            color={colors.tertiary}
          />
          <StatCard 
            icon={<Plane size={32} />} 
            title="Aircraft Inventory" 
            value={totalInventory} 
            color={colors.primary}
          />
          <StatCard 
            icon={<ListTodo size={32} />} 
            title="Pending Tasks" 
            value={pendingTasks} 
            total={tasks.length}
            color={colors.secondary}
          />
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          <div className="bg-white rounded-lg shadow-lg p-6">
            <h3 className="text-xl font-semibold mb-4" style={{ color: colors.primary }}>Recent Leads</h3>
            <div className="space-y-3">
              {leads.slice(0, 5).map(lead => (
                <div key={lead.id} className="flex justify-between items-center p-3 bg-gray-50 rounded">
                  <div>
                    <p className="font-medium">{lead.name}</p>
                    <p className="text-sm text-gray-600">{lead.company}</p>
                  </div>
                  <span className={`px-3 py-1 rounded-full text-xs font-semibold ${
                    lead.status === 'Hot' ? 'bg-red-100 text-red-700' :
                    lead.status === 'Warm' ? 'bg-orange-100 text-orange-700' :
                    'bg-blue-100 text-blue-700'
                  }`}>
                    {lead.status}
                  </span>
                </div>
              ))}
            </div>
          </div>

          <div className="bg-white rounded-lg shadow-lg p-6">
            <h3 className="text-xl font-semibold mb-4" style={{ color: colors.primary }}>Upcoming Tasks</h3>
            <div className="space-y-3">
              {tasks.filter(t => t.status === 'pending').slice(0, 5).map(task => (
                <div key={task.id} className="flex justify-between items-center p-3 bg-gray-50 rounded">
                  <div className="flex-1">
                    <p className="font-medium">{task.title}</p>
                    <p className="text-sm text-gray-600">{task.dueDate}</p>
                  </div>
                  <button
                    onClick={() => updateTask(task.id, { status: 'completed' })}
                    className="ml-2 p-1 hover:bg-green-100 rounded"
                  >
                    <Check size={20} style={{ color: colors.secondary }} />
                  </button>
                </div>
              ))}
            </div>
          </div>
        </div>

        <div className="bg-white rounded-lg shadow-lg p-6">
          <h3 className="text-xl font-semibold mb-4" style={{ color: colors.primary }}>Deal Pipeline</h3>
          <div className="grid grid-cols-2 md:grid-cols-4 lg:grid-cols-8 gap-4">
            {['Lead', 'Qualification', 'Presentation', 'Negotiation', 'Pre-Purchase', 'Closing', 'Closed Won', 'Closed Lost'].map(status => {
              const count = deals.filter(d => d.status === status).length;
              return (
                <div key={status} className="text-center p-4 bg-gray-50 rounded">
                  <p className="text-2xl font-bold" style={{ color: colors.primary }}>{count}</p>
                  <p className="text-xs text-gray-600 mt-1">{status}</p>
                </div>
              );
            })}
          </div>
        </div>
      </div>
    );
  };

  // Leads Component
  const LeadsView = () => {
    const filteredLeads = leads.filter(lead => {
      const matchesSearch = lead.name.toLowerCase().includes(searchTerm.toLowerCase()) ||
                           lead.company.toLowerCase().includes(searchTerm.toLowerCase());
      const matchesFilter = filterStatus === 'all' || lead.status === filterStatus;
      return matchesSearch && matchesFilter;
    });

    return (
      <div className="space-y-6">
        <div className="flex justify-between items-center">
          <h2 className="text-2xl font-bold" style={{ color: colors.primary }}>Leads</h2>
          <button
            onClick={() => openModal('lead')}
            className="flex items-center gap-2 px-4 py-2 rounded-lg text-white"
            style={{ backgroundColor: colors.secondary }}
          >
            <Plus size={20} /> Add Lead
          </button>
        </div>

        <div className="flex gap-4 items-center">
          <div className="flex-1 relative">
            <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400" size={20} />
            <input
              type="text"
              placeholder="Search leads..."
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              className="w-full pl-10 pr-4 py-2 border rounded-lg"
            />
          </div>
          <select
            value={filterStatus}
            onChange={(e) => setFilterStatus(e.target.value)}
            className="px-4 py-2 border rounded-lg"
          >
            <option value="all">All Status</option>
            <option value="Hot">Hot</option>
            <option value="Warm">Warm</option>
            <option value="Cold">Cold</option>
          </select>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          {filteredLeads.map(lead => (
            <div key={lead.id} className="bg-white rounded-lg shadow-lg p-6">
              <div className="flex justify-between items-start mb-4">
                <div>
                  <h3 className="text-xl font-semibold" style={{ color: colors.primary }}>{lead.name}</h3>
                  <p className="text-gray-600">{lead.company}</p>
                </div>
                <div className="flex gap-2">
                  <button
                    onClick={() => openModal('lead', lead)}
                    className="p-2 hover:bg-gray-100 rounded"
                  >
                    <Edit2 size={18} />
                  </button>
                  <button
                    onClick={() => deleteLead(lead.id)}
                    className="p-2 hover:bg-red-100 rounded"
                  >
                    <Trash2 size={18} className="text-red-600" />
                  </button>
                </div>
              </div>

              <div className="space-y-2 mb-4">
                <div className="flex justify-between">
                  <span className="text-gray-600">Aircraft Type:</span>
                  <span className="font-medium">{lead.aircraftType}</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-gray-600">Budget:</span>
                  <span className="font-medium">
                    {lead.budgetKnown ? `$${(lead.budget / 1000000).toFixed(1)}M` : 'Unknown'}
                  </span>
                </div>
                <div className="flex justify-between">
                  <span className="text-gray-600">Year Preference:</span>
                  <span className="font-medium">
                    {lead.yearPreference.oldest} - {lead.yearPreference.newest}
                  </span>
                </div>
                <div className="flex justify-between">
                  <span className="text-gray-600">Status:</span>
                  <span className={`px-3 py-1 rounded-full text-xs font-semibold ${
                    lead.status === 'Hot' ? 'bg-red-100 text-red-700' :
                    lead.status === 'Warm' ? 'bg-orange-100 text-orange-700' :
                    'bg-blue-100 text-blue-700'
                  }`}>
                    {lead.status}
                  </span>
                </div>
              </div>

              {lead.presentations.length > 0 && (
                <div className="mt-4 pt-4 border-t">
                  <h4 className="font-semibold mb-2" style={{ color: colors.primary }}>
                    Presentations ({lead.presentations.length})
                  </h4>
                  <div className="space-y-2">
                    {lead.presentations.map((pres, idx) => {
                      const ac = aircraft.find(a => a.id === pres.aircraftId);
                      return (
                        <div key={idx} className="text-sm bg-gray-50 p-2 rounded">
                          <p className="font-medium">{ac?.manufacturer} {ac?.model}</p>
                          <p className="text-gray-600">Price: ${(pres.priceGiven / 1000000).toFixed(1)}M</p>
                          <p className="text-gray-500 text-xs">{new Date(pres.date).toLocaleDateString()}</p>
                        </div>
                      );
                    })}
                  </div>
                </div>
              )}

              <div className="mt-4 flex gap-2">
                <button
                  onClick={() => openModal('presentation', lead)}
                  className="flex-1 px-4 py-2 rounded-lg text-white"
                  style={{ backgroundColor: colors.primary }}
                >
                  Present Aircraft
                </button>
                <button
                  onClick={() => openModal('dealFromLead', lead)}
                  className="flex-1 px-4 py-2 rounded-lg text-white"
                  style={{ backgroundColor: colors.secondary }}
                >
                  Create Deal
                </button>
              </div>
            </div>
          ))}
        </div>
      </div>
    );
  };

  // Aircraft Component
  const AircraftView = () => {
    return (
      <div className="space-y-6">
        <div className="flex justify-between items-center">
          <h2 className="text-2xl font-bold" style={{ color: colors.primary }}>Aircraft Inventory</h2>
          <button
            onClick={() => openModal('aircraft')}
            className="flex items-center gap-2 px-4 py-2 rounded-lg text-white"
            style={{ backgroundColor: colors.secondary }}
          >
            <Plus size={20} /> Add Aircraft
          </button>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-2 xl:grid-cols-3 gap-6">
          {aircraft.map(ac => (
            <div key={ac.id} className="bg-white rounded-lg shadow-lg overflow-hidden">
              <div className="p-6">
                <div className="flex justify-between items-start mb-4">
                  <div>
                    <h3 className="text-xl font-semibold" style={{ color: colors.primary }}>
                      {ac.manufacturer} {ac.model}
                    </h3>
                    <p className="text-gray-600">{ac.yom}</p>
                  </div>
                  <div className="flex gap-2">
                    <button
                      onClick={() => openModal('aircraft', ac)}
                      className="p-2 hover:bg-gray-100 rounded"
                    >
                      <Edit2 size={18} />
                    </button>
                    <button
                      onClick={() => deleteAircraft(ac.id)}
                      className="p-2 hover:bg-red-100 rounded"
                    >
                      <Trash2 size={18} className="text-red-600" />
                    </button>
                  </div>
                </div>

                <div className="space-y-2 mb-4">
                  <div className="flex justify-between text-sm">
                    <span className="text-gray-600">Category:</span>
                    <span className="font-medium">{ac.category}</span>
                  </div>
                  <div className="flex justify-between text-sm">
                    <span className="text-gray-600">Serial Number:</span>
                    <span className="font-medium">{ac.serialNumber}</span>
                  </div>
                  <div className="flex justify-between text-sm">
                    <span className="text-gray-600">Registration:</span>
                    <span className="font-medium">{ac.registration}</span>
                  </div>
                  <div className="flex justify-between text-sm">
                    <span className="text-gray-600">Location:</span>
                    <span className="font-medium">{ac.location}</span>
                  </div>
                  <div className="flex justify-between text-sm">
                    <span className="text-gray-600">Access Type:</span>
                    <span className="font-medium">{ac.accessType}</span>
                  </div>
                  <div className="flex justify-between text-lg font-bold pt-2 border-t">
                    <span style={{ color: colors.primary }}>Price:</span>
                    <span style={{ color: colors.secondary }}>${(ac.price / 1000000).toFixed(1)}M</span>
                  </div>
                </div>

                {ac.presentations.length > 0 && (
                  <div className="mt-4 pt-4 border-t">
                    <h4 className="font-semibold mb-2" style={{ color: colors.primary }}>
                      Presented to ({ac.presentations.length})
                    </h4>
                    <div className="space-y-2">
                      {ac.presentations.map((pres, idx) => {
                        const lead = leads.find(l => l.id === pres.leadId);
                        return (
                          <div key={idx} className="text-sm bg-gray-50 p-2 rounded">
                            <p className="font-medium">{lead?.name}</p>
                            <p className="text-gray-500 text-xs">{new Date(pres.date).toLocaleDateString()}</p>
                          </div>
                        );
                      })}
                    </div>
                  </div>
                )}

                <button
                  onClick={() => openModal('presentationFromAircraft', ac)}
                  className="w-full mt-4 px-4 py-2 rounded-lg text-white"
                  style={{ backgroundColor: colors.primary }}
                >
                  Present to Lead
                </button>
              </div>
            </div>
          ))}
        </div>
      </div>
    );
  };

  // Deals Component
  const DealsView = () => {
    return (
      <div className="space-y-6">
        <div className="flex justify-between items-center">
          <h2 className="text-2xl font-bold" style={{ color: colors.primary }}>Deals</h2>
          <button
            onClick={() => openModal('deal')}
            className="flex items-center gap-2 px-4 py-2 rounded-lg text-white"
            style={{ backgroundColor: colors.secondary }}
          >
            <Plus size={20} /> Add Deal
          </button>
        </div>

        <div className="space-y-4">
          {deals.map(deal => {
            const lead = leads.find(l => l.id === deal.relatedLead);
            const ac = aircraft.find(a => a.id === deal.relatedAircraft);
            
            return (
              <div key={deal.id} className="bg-white rounded-lg shadow-lg p-6">
                <div className="flex justify-between items-start mb-4">
                  <div className="flex-1">
                    <h3 className="text-xl font-semibold" style={{ color: colors.primary }}>{deal.dealName}</h3>
                    <p className="text-gray-600">{deal.clientName}</p>
                  </div>
                  <div className="flex gap-2">
                    <button
                      onClick={() => openModal('deal', deal)}
                      className="p-2 hover:bg-gray-100 rounded"
                    >
                      <Edit2 size={18} />
                    </button>
                    <button
                      onClick={() => deleteDeal(deal.id)}
                      className="p-2 hover:bg-red-100 rounded"
                    >
                      <Trash2 size={18} className="text-red-600" />
                    </button>
                  </div>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4 mb-4">
                  <div>
                    <p className="text-sm text-gray-600">Aircraft</p>
                    <p className="font-medium">{ac?.manufacturer} {ac?.model}</p>
                  </div>
                  <div>
                    <p className="text-sm text-gray-600">Deal Value</p>
                    <p className="font-medium text-lg" style={{ color: colors.secondary }}>
                      ${(deal.dealValue / 1000000).toFixed(1)}M
                    </p>
                  </div>
                  <div>
                    <p className="text-sm text-gray-600">Est. Closing</p>
                    <p className="font-medium">{deal.estimatedClosing}</p>
                  </div>
                </div>

                <div className="mb-4">
                  <p className="text-sm text-gray-600 mb-2">Status</p>
                  <select
                    value={deal.status}
                    onChange={(e) => updateDealStatus(deal.id, e.target.value)}
                    className="w-full md:w-auto px-4 py-2 border rounded-lg font-medium"
                    style={{ color: colors.primary }}
                  >
                    <option value="Lead">Lead</option>
                    <option value="Qualification">Qualification</option>
                    <option value="Presentation">Presentation</option>
                    <option value="Negotiation">Negotiation</option>
                    <option value="Pre-Purchase">Pre-Purchase</option>
                    <option value="Closing">Closing</option>
                    <option value="Closed Won">Closed Won</option>
                    <option value="Closed Lost">Closed Lost</option>
                  </select>
                </div>

                <div className="bg-gray-50 rounded-lg p-4">
                  <div className="flex items-start gap-3">
                    <Clock size={20} style={{ color: colors.secondary }} className="mt-1" />
                    <div className="flex-1">
                      <p className="font-semibold" style={{ color: colors.primary }}>Next Step</p>
                      <p className="text-gray-700">{deal.nextStep}</p>
                      <p className="text-sm text-gray-600 mt-1">Follow-up: {deal.followUpDate}</p>
                    </div>
                  </div>
                </div>

                {deal.history && deal.history.length > 1 && (
                  <div className="mt-4 pt-4 border-t">
                    <p className="font-semibold mb-2" style={{ color: colors.primary }}>History</p>
                    <div className="space-y-2">
                      {deal.history.slice(-3).reverse().map((h, idx) => (
                        <div key={idx} className="text-sm text-gray-600">
                          <span className="font-medium">{new Date(h.date).toLocaleDateString()}</span> - {h.action}
                        </div>
                      ))}
                    </div>
                  </div>
                )}
              </div>
            );
          })}
        </div>
      </div>
    );
  };

  // Tasks Component
  const TasksView = () => {
    const sortedTasks = [...tasks].sort((a, b) => new Date(a.dueDate) - new Date(b.dueDate));
    const pendingTasks = sortedTasks.filter(t => t.status === 'pending');
    const completedTasks = sortedTasks.filter(t => t.status === 'completed');

    if (calendarView) {
      return <TasksCalendarView tasks={pendingTasks} onBack={() => setCalendarView(false)} />;
    }

    return (
      <div className="space-y-6">
        <div className="flex justify-between items-center">
          <h2 className="text-2xl font-bold" style={{ color: colors.primary }}>Tasks</h2>
          <div className="flex gap-2">
            <button
              onClick={() => setCalendarView(true)}
              className="flex items-center gap-2 px-4 py-2 rounded-lg border"
              style={{ borderColor: colors.primary, color: colors.primary }}
            >
              <Calendar size={20} /> Calendar View
            </button>
            <button
              onClick={() => openModal('task')}
              className="flex items-center gap-2 px-4 py-2 rounded-lg text-white"
              style={{ backgroundColor: colors.secondary }}
            >
              <Plus size={20} /> Add Task
            </button>
          </div>
        </div>

        <div className="bg-white rounded-lg shadow-lg p-6">
          <h3 className="text-lg font-semibold mb-4" style={{ color: colors.primary }}>
            Pending Tasks ({pendingTasks.length})
          </h3>
          <div className="space-y-3">
            {pendingTasks.map(task => (
              <TaskCard key={task.id} task={task} onUpdate={updateTask} onDelete={deleteTask} />
            ))}
            {pendingTasks.length === 0 && (
              <p className="text-gray-500 text-center py-8">No pending tasks</p>
            )}
          </div>
        </div>

        {completedTasks.length > 0 && (
          <div className="bg-white rounded-lg shadow-lg p-6">
            <h3 className="text-lg font-semibold mb-4" style={{ color: colors.primary }}>
              Completed Tasks ({completedTasks.length})
            </h3>
            <div className="space-y-3">
              {completedTasks.slice(0, 10).map(task => (
                <TaskCard key={task.id} task={task} onUpdate={updateTask} onDelete={deleteTask} />
              ))}
            </div>
          </div>
        )}
      </div>
    );
  };

  // Task Card Component
  const TaskCard = ({ task, onUpdate, onDelete }) => {
    const isOverdue = new Date(task.dueDate) < new Date() && task.status === 'pending';
    
    return (
      <div className={`flex items-center gap-4 p-4 rounded-lg ${
        task.status === 'completed' ? 'bg-green-50' : isOverdue ? 'bg-red-50' : 'bg-gray-50'
      }`}>
        <button
          onClick={() => onUpdate(task.id, { status: task.status === 'pending' ? 'completed' : 'pending' })}
          className={`p-2 rounded border-2 ${
            task.status === 'completed' 
              ? 'bg-green-500 border-green-500' 
              : 'border-gray-300 hover:border-green-500'
          }`}
        >
          {task.status === 'completed' && <Check size={16} className="text-white" />}
        </button>
        
        <div className="flex-1">
          <div className="flex items-start justify-between">
            <div>
              <p className={`font-medium ${task.status === 'completed' ? 'line-through text-gray-500' : ''}`}>
                {task.title}
              </p>
              <p className="text-sm text-gray-600">{task.description}</p>
              <div className="flex gap-3 mt-2 text-xs text-gray-500">
                <span>Due: {task.dueDate}</span>
                <span className={`px-2 py-1 rounded ${
                  task.priority === 'high' ? 'bg-red-100 text-red-700' :
                  task.priority === 'medium' ? 'bg-orange-100 text-orange-700' :
                  'bg-blue-100 text-blue-700'
                }`}>
                  {task.priority}
                </span>
                {task.autoGenerated && (
                  <span className="px-2 py-1 rounded bg-purple-100 text-purple-700">Auto</span>
                )}
              </div>
            </div>
            <button
              onClick={() => onDelete(task.id)}
              className="p-2 hover:bg-red-100 rounded"
            >
              <Trash2 size={16} className="text-red-600" />
            </button>
          </div>
        </div>
      </div>
    );
  };

  // Calendar View for Tasks
  const TasksCalendarView = ({ tasks, onBack }) => {
    const [currentMonth, setCurrentMonth] = useState(new Date());
    
    const getDaysInMonth = (date) => {
      const year = date.getFullYear();
      const month = date.getMonth();
      const firstDay = new Date(year, month, 1);
      const lastDay = new Date(year, month + 1, 0);
      const daysInMonth = lastDay.getDate();
      const startingDayOfWeek = firstDay.getDay();
      
      return { daysInMonth, startingDayOfWeek, year, month };
    };

    const { daysInMonth, startingDayOfWeek, year, month } = getDaysInMonth(currentMonth);
    const days = Array.from({ length: daysInMonth }, (_, i) => i + 1);
    const blanks = Array.from({ length: startingDayOfWeek }, (_, i) => i);

    const getTasksForDate = (day) => {
      const dateStr = `${year}-${String(month + 1).padStart(2, '0')}-${String(day).padStart(2, '0')}`;
      return tasks.filter(t => t.dueDate === dateStr);
    };

    const monthNames = ['January', 'February', 'March', 'April', 'May', 'June',
                       'July', 'August', 'September', 'October', 'November', 'December'];

    return (
      <div className="space-y-6">
        <div className="flex justify-between items-center">
          <button
            onClick={onBack}
            className="flex items-center gap-2 px-4 py-2 rounded-lg border"
            style={{ borderColor: colors.primary, color: colors.primary }}
          >
            ← Back to List
          </button>
          <h2 className="text-2xl font-bold" style={{ color: colors.primary }}>Task Calendar</h2>
          <div className="w-32"></div>
        </div>

        <div className="bg-white rounded-lg shadow-lg p-6">
          <div className="flex justify-between items-center mb-6">
            <button
              onClick={() => setCurrentMonth(new Date(year, month - 1))}
              className="p-2 hover:bg-gray-100 rounded"
            >
              <ChevronDown className="transform rotate-90" />
            </button>
            <h3 className="text-xl font-semibold" style={{ color: colors.primary }}>
              {monthNames[month]} {year}
            </h3>
            <button
              onClick={() => setCurrentMonth(new Date(year, month + 1))}
              className="p-2 hover:bg-gray-100 rounded"
            >
              <ChevronDown className="transform -rotate-90" />
            </button>
          </div>

          <div className="grid grid-cols-7 gap-2">
            {['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'].map(day => (
              <div key={day} className="text-center font-semibold p-2" style={{ color: colors.primary }}>
                {day}
              </div>
            ))}
            
            {blanks.map(i => (
              <div key={`blank-${i}`} className="p-2 h-24"></div>
            ))}
            
            {days.map(day => {
              const dayTasks = getTasksForDate(day);
              const isToday = new Date().getDate() === day && 
                             new Date().getMonth() === month && 
                             new Date().getFullYear() === year;
              
              return (
                <div
                  key={day}
                  className={`p-2 h-24 border rounded-lg ${isToday ? 'border-2' : ''}`}
                  style={isToday ? { borderColor: colors.secondary } : {}}
                >
                  <div className="font-medium mb-1">{day}</div>
                  <div className="space-y-1">
                    {dayTasks.slice(0, 2).map(task => (
                      <div
                        key={task.id}
                        className="text-xs p-1 rounded truncate"
                        style={{ backgroundColor: colors.primary, color: 'white' }}
                        title={task.title}
                      >
                        {task.title}
                      </div>
                    ))}
                    {dayTasks.length > 2 && (
                      <div className="text-xs text-gray-500">+{dayTasks.length - 2} more</div>
                    )}
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      </div>
    );
  };

  // AI Assistant Component
  const AIAssistant = () => {
    return (
      <div className="fixed bottom-6 right-6 z-50">
        <div className="bg-white rounded-lg shadow-2xl w-96 max-h-[600px] flex flex-col">
          <div className="p-4 rounded-t-lg flex justify-between items-center" style={{ backgroundColor: colors.primary }}>
            <div className="flex items-center gap-2 text-white">
              <Bot size={24} />
              <span className="font-semibold">AI Assistant</span>
            </div>
          </div>

          <div className="flex-1 overflow-y-auto p-4 space-y-3 max-h-[400px]">
            {aiMessages.length === 0 ? (
              <div className="text-center text-gray-500 py-8">
                <Bot size={48} className="mx-auto mb-3 text-gray-300" />
                <p>Hi! I'm your AI assistant.</p>
                <p className="text-sm mt-2">Ask me to help with leads, aircraft, deals, or tasks!</p>
              </div>
            ) : (
              aiMessages.map((msg, idx) => (
                <div
                  key={idx}
                  className={`p-3 rounded-lg ${
                    msg.role === 'user' 
                      ? 'ml-8' 
                      : 'mr-8'
                  }`}
                  style={{
                    backgroundColor: msg.role === 'user' ? colors.primary : colors.silver,
                    color: msg.role === 'user' ? 'white' : colors.primary
                  }}
                >
                  {msg.content}
                </div>
              ))
            )}
            {isAiThinking && (
              <div className="flex items-center gap-2 text-gray-500 p-3">
                <div className="animate-pulse">●</div>
                <div className="animate-pulse" style={{ animationDelay: '0.2s' }}>●</div>
                <div className="animate-pulse" style={{ animationDelay: '0.4s' }}>●</div>
              </div>
            )}
          </div>

          <div className="p-4 border-t">
            <div className="flex gap-2">
              <input
                type="text"
                value={aiInput}
                onChange={(e) => setAiInput(e.target.value)}
                onKeyPress={(e) => e.key === 'Enter' && handleAiMessage()}
                placeholder="Ask me anything..."
                className="flex-1 px-4 py-2 border rounded-lg focus:outline-none focus:ring-2"
                style={{ focusRingColor: colors.primary }}
              />
              <button
                onClick={handleAiMessage}
                className="p-2 rounded-lg text-white"
                style={{ backgroundColor: colors.secondary }}
                disabled={isAiThinking || !aiInput.trim()}
              >
                <Send size={20} />
              </button>
            </div>
          </div>
        </div>
      </div>
    );
  };

  // Modal Component
  const Modal = () => {
    if (!showModal) return null;

    const [formData, setFormData] = useState(editingItem || {});

    const handleSubmit = () => {
      if (modalType === 'lead') {
        if (editingItem) {
          updateLead(editingItem.id, formData);
        } else {
          addLead(formData);
        }
      } else if (modalType === 'aircraft') {
        if (editingItem) {
          updateAircraft(editingItem.id, formData);
        } else {
          addAircraft(formData);
        }
      } else if (modalType === 'deal' || modalType === 'dealFromLead') {
        if (editingItem && modalType === 'deal') {
          setDeals(deals.map(d => d.id === editingItem.id ? { ...d, ...formData } : d));
        } else {
          addDeal(formData);
        }
      } else if (modalType === 'task') {
        if (editingItem) {
          updateTask(editingItem.id, formData);
        } else {
          addTask(formData);
        }
      } else if (modalType === 'presentation' || modalType === 'presentationFromAircraft') {
        const leadId = modalType === 'presentation' ? editingItem.id : formData.leadId;
        const aircraftId = modalType === 'presentationFromAircraft' ? editingItem.id : formData.aircraftId;
        presentAircraftToLead(leadId, aircraftId, formData.notes, formData.price);
      }
      closeModal();
    };

    return (
      <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
        <div className="bg-white rounded-lg shadow-xl max-w-2xl w-full max-h-[90vh] overflow-y-auto">
          <div className="p-6 border-b flex justify-between items-center" style={{ backgroundColor: colors.primary }}>
            <h3 className="text-xl font-semibold text-white">
              {editingItem ? 'Edit' : 'Add'} {modalType === 'dealFromLead' ? 'Deal' : modalType === 'presentationFromAircraft' || modalType === 'presentation' ? 'Presentation' : modalType.charAt(0).toUpperCase() + modalType.slice(1)}
            </h3>
            <button onClick={closeModal} className="text-white hover:bg-opacity-80 p-1 rounded">
              <X size={24} />
            </button>
          </div>

          <div className="p-6">
            {modalType === 'lead' && (
              <div className="space-y-4">
                <input
                  type="text"
                  placeholder="Name *"
                  value={formData.name || ''}
                  onChange={(e) => setFormData({ ...formData, name: e.target.value })}
                  className="w-full px-4 py-2 border rounded-lg"
                />
                <input
                  type="text"
                  placeholder="Company"
                  value={formData.company || ''}
                  onChange={(e) => setFormData({ ...formData, company: e.target.value })}
                  className="w-full px-4 py-2 border rounded-lg"
                />
                <select
                  value={formData.aircraftType || ''}
                  onChange={(e) => setFormData({ ...formData, aircraftType: e.target.value })}
                  className="w-full px-4 py-2 border rounded-lg"
                >
                  <option value="">Select Aircraft Type</option>
                  <option value="Light Jet">Light Jet</option>
                  <option value="Midsize Jet">Midsize Jet</option>
                  <option value="Heavy Jet">Heavy Jet</option>
                  <option value="Ultra-Long Range">Ultra-Long Range</option>
                </select>
                <div className="flex gap-4 items-center">
                  <label className="flex items-center gap-2">
                    <input
                      type="checkbox"
                      checked={formData.budgetKnown || false}
                      onChange={(e) => setFormData({ ...formData, budgetKnown: e.target.checked })}
                    />
                    Budget Known
                  </label>
                  {formData.budgetKnown && (
                    <input
                      type="number"
                      placeholder="Budget (USD)"
                      value={formData.budget || ''}
                      onChange={(e) => setFormData({ ...formData, budget: Number(e.target.value) })}
                      className="flex-1 px-4 py-2 border rounded-lg"
                    />
                  )}
                </div>
                <div className="grid grid-cols-2 gap-4">
                  <input
                    type="number"
                    placeholder="Oldest Year"
                    value={formData.yearPreference?.oldest || ''}
                    onChange={(e) => setFormData({ 
                      ...formData, 
                      yearPreference: { ...formData.yearPreference, oldest: Number(e.target.value) }
                    })}
                    className="w-full px-4 py-2 border rounded-lg"
                  />
                  <input
                    type="number"
                    placeholder="Newest Year"
                    value={formData.yearPreference?.newest || ''}
                    onChange={(e) => setFormData({ 
                      ...formData, 
                      yearPreference: { ...formData.yearPreference, newest: Number(e.target.value) }
                    })}
                    className="w-full px-4 py-2 border rounded-lg"
                  />
                </div>
                <select
                  value={formData.status || 'Cold'}
                  onChange={(e) => setFormData({ ...formData, status: e.target.value })}
                  className="w-full px-4 py-2 border rounded-lg"
                >
                  <option value="Hot">Hot</option>
                  <option value="Warm">Warm</option>
                  <option value="Cold">Cold</option>
                </select>
                <textarea
                  placeholder="Notes"
                  value={formData.notes || ''}
                  onChange={(e) => setFormData({ ...formData, notes: e.target.value })}
                  className="w-full px-4 py-2 border rounded-lg h-24"
                />
              </div>
            )}

            {modalType === 'aircraft' && (
              <div className="space-y-4">
                <input
                  type="text"
                  placeholder="Manufacturer *"
                  value={formData.manufacturer || ''}
                  onChange={(e) => setFormData({ ...formData, manufacturer: e.target.value })}
                  className="w-full px-4 py-2 border rounded-lg"
                />
                <input
                  type="text"
                  placeholder="Model *"
                  value={formData.model || ''}
                  onChange={(e) => setFormData({ ...formData, model: e.target.value })}
                  className="w-full px-4 py-2 border rounded-lg"
                />
                <div className="grid grid-cols-2 gap-4">
                  <input
                    type="number"
                    placeholder="Year of Manufacture *"
                    value={formData.yom || ''}
                    onChange={(e) => setFormData({ ...formData, yom: Number(e.target.value) })}
                    className="w-full px-4 py-2 border rounded-lg"
                  />
                  <input
                    type="text"
                    placeholder="Serial Number"
                    value={formData.serialNumber || ''}
                    onChange={(e) => setFormData({ ...formData, serialNumber: e.target.value })}
                    className="w-full px-4 py-2 border rounded-lg"
                  />
                </div>
                <input
                  type="text"
                  placeholder="Registration"
                  value={formData.registration || ''}
                  onChange={(e) => setFormData({ ...formData, registration: e.target.value })}
                  className="w-full px-4 py-2 border rounded-lg"
                />
                <select
                  value={formData.category || ''}
                  onChange={(e) => setFormData({ ...formData, category: e.target.value })}
                  className="w-full px-4 py-2 border rounded-lg"
                >
                  <option value="">Select Category</option>
                  <option value="Light Jet">Light Jet</option>
                  <option value="Midsize Jet">Midsize Jet</option>
                  <option value="Heavy Jet">Heavy Jet</option>
                  <option value="Ultra-Long Range">Ultra-Long Range</option>
                </select>
                <input
                  type="text"
                  placeholder="Location"
                  value={formData.location || ''}
                  onChange={(e) => setFormData({ ...formData, location: e.target.value })}
                  className="w-full px-4 py-2 border rounded-lg"
                />
                <input
                  type="number"
                  placeholder="Price (USD) *"
                  value={formData.price || ''}
                  onChange={(e) => setFormData({ ...formData, price: Number(e.target.value) })}
                  className="w-full px-4 py-2 border rounded-lg"
                />
                <select
                  value={formData.accessType || 'Direct'}
                  onChange={(e) => setFormData({ ...formData, accessType: e.target.value })}
                  className="w-full px-4 py-2 border rounded-lg"
                >
                  <option value="Direct">Direct Access</option>
                  <option value="Broker">Through Broker</option>
                  <option value="Intermediary">Through Intermediary</option>
                </select>
                <div className="border-2 border-dashed rounded-lg p-6 text-center">
                  <Upload className="mx-auto mb-2 text-gray-400" size={32} />
                  <p className="text-sm text-gray-600">Upload Spec Sheet (AI will extract info)</p>
                  <input type="file" className="hidden" accept=".pdf,.doc,.docx" />
                  <button className="mt-2 px-4 py-2 text-sm border rounded-lg hover:bg-gray-50">
                    Choose File
                  </button>
                </div>
              </div>
            )}

            {(modalType === 'deal' || modalType === 'dealFromLead') && (
              <div className="space-y-4">
                <input
                  type="text"
                  placeholder="Deal Name *"
                  value={formData.dealName || ''}
                  onChange={(e) => setFormData({ ...formData, dealName: e.target.value })}
                  className="w-full px-4 py-2 border rounded-lg"
                />
                <input
                  type="text"
                  placeholder="Client Name *"
                  value={formData.clientName || (modalType === 'dealFromLead' ? editingItem?.name : '')}
                  onChange={(e) => setFormData({ ...formData, clientName: e.target.value })}
                  className="w-full px-4 py-2 border rounded-lg"
                />
                <select
                  value={formData.relatedLead || (modalType === 'dealFromLead' ? editingItem?.id : '')}
                  onChange={(e) => setFormData({ ...formData, relatedLead: Number(e.target.value) })}
                  className="w-full px-4 py-2 border rounded-lg"
                >
                  <option value="">Select Related Lead</option>
                  {leads.map(lead => (
                    <option key={lead.id} value={lead.id}>{lead.name}</option>
                  ))}
                </select>
                <select
                  value={formData.relatedAircraft || ''}
                  onChange={(e) => setFormData({ ...formData, relatedAircraft: Number(e.target.value) })}
                  className="w-full px-4 py-2 border rounded-lg"
                >
                  <option value="">Select Aircraft</option>
                  {aircraft.map(ac => (
                    <option key={ac.id} value={ac.id}>{ac.manufacturer} {ac.model} - ${(ac.price / 1000000).toFixed(1)}M</option>
                  ))}
                </select>
                <input
                  type="number"
                  placeholder="Deal Value (USD) *"
                  value={formData.dealValue || ''}
                  onChange={(e) => setFormData({ ...formData, dealValue: Number(e.target.value) })}
                  className="w-full px-4 py-2 border rounded-lg"
                />
                <input
                  type="date"
                  placeholder="Estimated Closing Date"
                  value={formData.estimatedClosing || ''}
                  onChange={(e) => setFormData({ ...formData, estimatedClosing: e.target.value })}
                  className="w-full px-4 py-2 border rounded-lg"
                />
                <select
                  value={formData.status || 'Lead'}
                  onChange={(e) => setFormData({ ...formData, status: e.target.value })}
                  className="w-full px-4 py-2 border rounded-lg"
                >
                  <option value="Lead">Lead</option>
                  <option value="Qualification">Qualification</option>
                  <option value="Presentation">Presentation</option>
                  <option value="Negotiation">Negotiation</option>
                  <option value="Pre-Purchase">Pre-Purchase</option>
                  <option value="Closing">Closing</option>
                </select>
                <input
                  type="text"
                  placeholder="Next Step"
                  value={formData.nextStep || ''}
                  onChange={(e) => setFormData({ ...formData, nextStep: e.target.value })}
                  className="w-full px-4 py-2 border rounded-lg"
                />
                <input
                  type="date"
                  placeholder="Follow-up Date"
                  value={formData.followUpDate || ''}
                  onChange={(e) => setFormData({ ...formData, followUpDate: e.target.value })}
                  className="w-full px-4 py-2 border rounded-lg"
                />
              </div>
            )}

            {modalType === 'task' && (
              <div className="space-y-4">
                <input
                  type="text"
                  placeholder="Task Title *"
                  value={formData.title || ''}
                  onChange={(e) => setFormData({ ...formData, title: e.target.value })}
                  className="w-full px-4 py-2 border rounded-lg"
                />
                <textarea
                  placeholder="Description"
                  value={formData.description || ''}
                  onChange={(e) => setFormData({ ...formData, description: e.target.value })}
                  className="w-full px-4 py-2 border rounded-lg h-24"
                />
                <input
                  type="date"
                  placeholder="Due Date *"
                  value={formData.dueDate || ''}
                  onChange={(e) => setFormData({ ...formData, dueDate: e.target.value })}
                  className="w-full px-4 py-2 border rounded-lg"
                />
                <select
                  value={formData.priority || 'medium'}
                  onChange={(e) => setFormData({ ...formData, priority: e.target.value })}
                  className="w-full px-4 py-2 border rounded-lg"
                >
                  <option value="high">High Priority</option>
                  <option value="medium">Medium Priority</option>
                  <option value="low">Low Priority</option>
                </select>
                <select
                  value={formData.status || 'pending'}
                  onChange={(e) => setFormData({ ...formData, status: e.target.value })}
                  className="w-full px-4 py-2 border rounded-lg"
                >
                  <option value="pending">Pending</option>
                  <option value="completed">Completed</option>
                </select>
              </div>
            )}

            {(modalType === 'presentation' || modalType === 'presentationFromAircraft') && (
              <div className="space-y-4">
                {modalType === 'presentation' && (
                  <select
                    value={formData.aircraftId || ''}
                    onChange={(e) => setFormData({ ...formData, aircraftId: Number(e.target.value) })}
                    className="w-full px-4 py-2 border rounded-lg"
                  >
                    <option value="">Select Aircraft *</option>
                    {aircraft.map(ac => (
                      <option key={ac.id} value={ac.id}>
                        {ac.manufacturer} {ac.model} ({ac.yom}) - ${(ac.price / 1000000).toFixed(1)}M
                      </option>
                    ))}
                  </select>
                )}
                {modalType === 'presentationFromAircraft' && (
                  <select
                    value={formData.leadId || ''}
                    onChange={(e) => setFormData({ ...formData, leadId: Number(e.target.value) })}
                    className="w-full px-4 py-2 border rounded-lg"
                  >
                    <option value="">Select Lead *</option>
                    {leads.map(lead => (
                      <option key={lead.id} value={lead.id}>
                        {lead.name} - {lead.company} ({lead.aircraftType})
                      </option>
                    ))}
                  </select>
                )}
                <input
                  type="number"
                  placeholder="Price Given (USD) *"
                  value={formData.price || ''}
                  onChange={(e) => setFormData({ ...formData, price: Number(e.target.value) })}
                  className="w-full px-4 py-2 border rounded-lg"
                />
                <textarea
                  placeholder="Presentation Notes"
                  value={formData.notes || ''}
                  onChange={(e) => setFormData({ ...formData, notes: e.target.value })}
                  className="w-full px-4 py-2 border rounded-lg h-32"
                />
              </div>
            )}

            <div className="flex gap-4 mt-6">
              <button
                onClick={handleSubmit}
                className="flex-1 px-6 py-3 rounded-lg text-white font-semibold"
                style={{ backgroundColor: colors.secondary }}
              >
                {editingItem ? 'Update' : 'Create'}
              </button>
              <button
                onClick={closeModal}
                className="flex-1 px-6 py-3 rounded-lg border-2 font-semibold"
                style={{ borderColor: colors.primary, color: colors.primary }}
              >
                Cancel
              </button>
            </div>
          </div>
        </div>
      </div>
    );
  };

  // Stat Card Component
  const StatCard = ({ icon, title, value, total, color }) => (
    <div className="bg-white rounded-lg shadow-lg p-6">
      <div className="flex items-center justify-between mb-4">
        <div style={{ color }}>{icon}</div>
        {total && (
          <span className="text-sm text-gray-500">{value} / {total}</span>
        )}
      </div>
      <h3 className="text-gray-600 text-sm mb-1">{title}</h3>
      <p className="text-3xl font-bold" style={{ color }}>{value}</p>
    </div>
  );

  // Main Navigation
  const Navigation = () => (
    <nav className="text-white p-6" style={{ backgroundColor: colors.primary }}>
      <div className="flex items-center gap-3 mb-8">
        <Plane size={32} style={{ color: colors.secondary }} />
        <h1 className="text-2xl font-bold">JetCRM</h1>
      </div>
      
      <div className="space-y-2">
        {[
          { id: 'dashboard', icon: <FileText size={20} />, label: 'Dashboard' },
          { id: 'leads', icon: <Users size={20} />, label: 'Leads' },
          { id: 'aircraft', icon: <Plane size={20} />, label: 'Aircraft' },
          { id: 'deals', icon: <FileText size={20} />, label: 'Deals' },
          { id: 'tasks', icon: <ListTodo size={20} />, label: 'Tasks' }
        ].map(item => (
          <button
            key={item.id}
            onClick={() => setActiveTab(item.id)}
            className={`w-full flex items-center gap-3 px-4 py-3 rounded-lg transition-colors ${
              activeTab === item.id ? 'bg-white bg-opacity-20' : 'hover:bg-white hover:bg-opacity-10'
            }`}
          >
            {item.icon}
            <span className="font-medium">{item.label}</span>
          </button>
        ))}
      </div>
    </nav>
  );

  return (
    <div className="min-h-screen flex" style={{ backgroundColor: '#f5f5f5' }}>
      <div className="w-64 flex-shrink-0">
        <Navigation />
      </div>
      
      <div className="flex-1 p-8 overflow-y-auto">
        {activeTab === 'dashboard' && <Dashboard />}
        {activeTab === 'leads' && <LeadsView />}
        {activeTab === 'aircraft' && <AircraftView />}
        {activeTab === 'deals' && <DealsView />}
        {activeTab === 'tasks' && <TasksView />}
      </div>

      <AIAssistant />
      <Modal />
    </div>
  );
};

export default JetCRM;